mail_default_sender: "SampleApp"
mail_host: "https://sampleapp2812.herokuapp.com"
mail_protocol: "http"
mail_server: "smtp.gmail.com"
mail_post: 587
mail_username: "dtvthe2@gmail.com"
mail_password: "Aa@123456!"
mail_authentication: "plain"
mail_enable_starttls_auto: true
provider: "AWS"
