length_minimum: 6
name_length_maximum: 50
email_length_maximum: 150
gravatar_user_size: 80
gravatar_post_size: 50
remember_me_checked: "1"
user_per_page: 10
micropost_per_page: 7
current_version: 1.2
hours_expire: 2
micropost_content_max_length: 140
picture_size: 5
accept_img_types: "image/jpeg,image/gif,image/png"
size_in_megabytes: 1024
minimagick_width: 400
minimagick_height: 400
